### ISSUE TITLE
java.lang.NoClassDefFoundError: org.luaj.vm2.lib.Bit32Lib$Bit32LibV

### ISSUE THREAD

**Issue by therealdt** [Netdex/android-usb-script#19]
Hello,

with the latest version from Izzy (1.2.0) I get the following error running any lua script (e.g. debug.lua). I'm running Android 13 (LineageOS).

```
E AndroidRuntime: Process: org.netdex.androidusbscript, PID: 28745
E AndroidRuntime: java.lang.NoClassDefFoundError: org.luaj.vm2.lib.Bit32Lib$Bit32LibV
E AndroidRuntime: 	at a2.b.Q2(Unknown Source:12)
E AndroidRuntime: 	at a2.b.i0(Unknown Source:11)
E AndroidRuntime: 	at y1.t.p1(Unknown Source:2)
E AndroidRuntime: 	at b2.o.a(Unknown Source:26)
E AndroidRuntime: 	at k2.c.d(Unknown Source:62)
E AndroidRuntime: 	at org.netdex.androidusbscript.service.LuaUsbService.g(Unknown Source:2)
E AndroidRuntime: 	at org.netdex.androidusbscript.service.LuaUsbService.e(Unknown Source:0)
E AndroidRuntime: 	at org.netdex.androidusbscript.service.LuaUsbService.a(Unknown Source:0)
E AndroidRuntime: 	at j2.a.run(Unknown Source:4)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by Netdex** [comment]
Hi, thanks for the report. It seems like luaj doesn't like having it's names scrambled by proguard so I just turned it off. I also published release 1.2.1 with these changes.
